/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.minhthang.ui;

import com.minhthang.DAO.MovieDAO;
import com.minhthang.core.Movie;
import java.io.File;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Time;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Minh Thắng
 */
public class AddMovieDialog extends javax.swing.JDialog {

    private MovieDAO movieDAO;
    private MovieGUI movieGUI;
    private Movie previousMovie = null;
    private boolean updateMode = false;

    /**
     * Creates new form AddMovieDialog
     */
    public AddMovieDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AddMovieDialog(MovieGUI movieGUI, MovieDAO movieDAO) {
        this(new javax.swing.JFrame(), true);
        this.movieGUI = movieGUI;
        this.movieDAO = movieDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelType = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelIntroduction = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldType = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldIntroduction = new javax.swing.JTextField();
        jLabelActor = new javax.swing.JLabel();
        jLabelDirector = new javax.swing.JLabel();
        jLabelCountry = new javax.swing.JLabel();
        jLabelLength = new javax.swing.JLabel();
        jTextFieldActors = new javax.swing.JTextField();
        jTextFieldCountry = new javax.swing.JTextField();
        jTextFieldLength = new javax.swing.JTextField();
        jTextFieldDirector = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldHinhAnh = new javax.swing.JTextField();
        jLabelday = new javax.swing.JLabel();
        jLabeltime = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jTextFieldTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm phim");

        jLabelType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/minhthang/app/image/key.png"))); // NOI18N
        jLabelType.setText("Type :");

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/minhthang/app/image/key.png"))); // NOI18N
        jLabelName.setText("Name :");

        jLabelIntroduction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIntroduction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/minhthang/app/image/key.png"))); // NOI18N
        jLabelIntroduction.setText("Introduction :");

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelActor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/minhthang/app/image/key.png"))); // NOI18N
        jLabelActor.setText("Actors :");

        jLabelDirector.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDirector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/minhthang/app/image/key.png"))); // NOI18N
        jLabelDirector.setText("Director :");

        jLabelCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCountry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/minhthang/app/image/key.png"))); // NOI18N
        jLabelCountry.setText("Country :");

        jLabelLength.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLength.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/minhthang/app/image/key.png"))); // NOI18N
        jLabelLength.setText("Length :");

        jTextFieldCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCountryActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/minhthang/app/image/key.png"))); // NOI18N
        jLabel1.setText("Image :");

        jLabelday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/minhthang/app/image/key.png"))); // NOI18N
        jLabelday.setText("Day :");

        jLabeltime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeltime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/minhthang/app/image/key.png"))); // NOI18N
        jLabeltime.setText("Time :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLength)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelIntroduction)
                                .addComponent(jLabelType, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldType, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIntroduction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTextFieldLength)
                            .addComponent(jTextFieldHinhAnh)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabeltime)
                            .addComponent(jLabelDirector)
                            .addComponent(jLabelActor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTextFieldDay)
                            .addComponent(jTextFieldTime)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldActors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDirector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelActor)
                    .addComponent(jTextFieldActors, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDirector)
                    .addComponent(jTextFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelIntroduction))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCountry)
                                .addComponent(jTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldIntroduction, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLength)
                    .addComponent(jTextFieldLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelday)
                    .addComponent(jTextFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltime)
                    .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(83, 83, 83)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        try {
            saveMovie();
        } catch (SQLException ex) {
            Logger.getLogger(AddMovieDialog.class.getName()).log(
                    Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCountryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);

        File f = fc.getSelectedFile();
        String fileName = f.getAbsolutePath();

        jTextFieldHinhAnh.setText(fileName);


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    protected void saveMovie() throws SQLException {
        String type = jTextFieldType.getText();
        String name = jTextFieldName.getText();
        String introduction = jTextFieldIntroduction.getText();
        String actor = jTextFieldActors.getText();
        String director = jTextFieldDirector.getText();
        String country = jTextFieldCountry.getText();
        String length = jTextFieldLength.getText();
        String image = jTextFieldHinhAnh.getText();
        String day = jTextFieldDay.getText();
        String time = jTextFieldTime.getText();

        Movie tempMovie = new Movie(movieDAO.generateId(), type, name, introduction, actor, director, country, length, image, day, time);
        try {
            movieDAO.addMovie(tempMovie);
            setVisible(false);
            dispose();
            movieGUI.process();

            JOptionPane.showMessageDialog(movieGUI,
                    "Movie added succesfully.",
                    "Movie Added",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(
                    movieGUI,
                    "Error saving : "
                    + exc.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelActor;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelIntroduction;
    private javax.swing.JLabel jLabelLength;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelday;
    private javax.swing.JLabel jLabeltime;
    private javax.swing.JTextField jTextFieldActors;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldHinhAnh;
    private javax.swing.JTextField jTextFieldIntroduction;
    private javax.swing.JTextField jTextFieldLength;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldTime;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
