/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.minhthang.ui;

import com.minhthang.DAO.MovieDAO;
import com.minhthang.core.Movie;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Minh Thắng
 */
public class updateMovieDialog extends javax.swing.JDialog {

    private MovieDAO movieDAO;
    private MovieGUI movieGUI;
    private Movie previousMovie = null;
    private boolean updateMode = false;

    /**
     * Creates new form updateMovieDialog
     */
    public updateMovieDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public updateMovieDialog(MovieGUI movieGUI, MovieDAO movieDAO, Movie thePreviousMovie, boolean theUpdateMode) {
        this(new javax.swing.JFrame(), true);
        this.movieGUI = movieGUI;
        this.movieDAO = movieDAO;
        this.previousMovie = thePreviousMovie;
        this.updateMode = theUpdateMode;
        if (updateMode) {
            populateGUI(previousMovie);
        }
    }

    public updateMovieDialog(MovieGUI movieGUI, MovieDAO movieDAO) {
        this(movieGUI, movieDAO, null, false);
    }

    private void populateGUI(Movie theMovie) {
        jTextFieldType.setText(theMovie.getType());
        jTextFieldName.setText(theMovie.getName());
        jTextAreaIntroduction.setText(theMovie.getIntroduction());
        jTextFieldActor.setText(theMovie.getActor());
        jTextFieldDirector.setText(theMovie.getDirector());
        jTextFieldCountry.setText(theMovie.getCountry());
        jTextFieldLength.setText(theMovie.getLength());
        jTextFieldImage.setText(theMovie.getImage());
        jTextFieldDay.setText(theMovie.getDay());
        jTextFieldTime.setText(theMovie.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelIntroduction = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jTextFieldType = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLabelCountry = new javax.swing.JLabel();
        jLabelDirector = new javax.swing.JLabel();
        jLabelLength = new javax.swing.JLabel();
        jLabelActor = new javax.swing.JLabel();
        jTextFieldActor = new javax.swing.JTextField();
        jTextFieldDirector = new javax.swing.JTextField();
        jTextFieldCountry = new javax.swing.JTextField();
        jTextFieldLength = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldImage = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaIntroduction = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jTextFieldTime = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập nhật phim");
        setBackground(new java.awt.Color(229, 75, 75));

        jLabelType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelType.setText("Type:");

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelName.setText("Name:");

        jLabelIntroduction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIntroduction.setText("Introduction:");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jTextFieldType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTypeActionPerformed(evt);
            }
        });

        jLabelCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCountry.setText("Country:");

        jLabelDirector.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDirector.setText("Director:");

        jLabelLength.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLength.setText("Length:");

        jLabelActor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelActor.setText("Actors:");

        jTextFieldActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActorActionPerformed(evt);
            }
        });

        jTextFieldDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDirectorActionPerformed(evt);
            }
        });

        jTextFieldCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCountryActionPerformed(evt);
            }
        });

        jTextFieldLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLengthActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Image:");

        jTextFieldImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImageActionPerformed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextAreaIntroduction.setColumns(20);
        jTextAreaIntroduction.setLineWrap(true);
        jTextAreaIntroduction.setRows(5);
        jScrollPane1.setViewportView(jTextAreaIntroduction);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Day:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelType)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabelIntroduction)
                                    .addComponent(jLabelLength)
                                    .addComponent(jLabel1))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldType)
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(jTextFieldLength)
                                    .addComponent(jTextFieldImage)
                                    .addComponent(jScrollPane1))))
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelActor)
                            .addComponent(jLabelDirector)
                            .addComponent(jLabelCountry)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jTextFieldDirector, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jTextFieldActor, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jTextFieldDay)
                    .addComponent(jTextFieldTime))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelActor)
                    .addComponent(jTextFieldActor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDirector)
                    .addComponent(jTextFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCountry)
                            .addComponent(jTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelIntroduction)
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelLength)
                                    .addComponent(jTextFieldLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179)))
                        .addComponent(jButton2)
                        .addGap(44, 44, 44)))
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTypeActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        try {
            saveMovie();
        } catch (SQLException ex) {
            Logger.getLogger(updateMovieDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextFieldImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImageActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);

        File f = fc.getSelectedFile();
        String fileName = f.getAbsolutePath();

        jTextFieldImage.setText(fileName);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLengthActionPerformed

    private void jTextFieldCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCountryActionPerformed

    private void jTextFieldDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDirectorActionPerformed

    private void jTextFieldActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActorActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public void saveMovie() throws SQLException {
        String type = jTextFieldType.getText();
        String name = jTextFieldName.getText();
        String introduction = jTextAreaIntroduction.getText();
        String actor = jTextFieldActor.getText();
        String director = jTextFieldDirector.getText();
        String country = jTextFieldCountry.getText();
        String length = jTextFieldLength.getText();
        String image = jTextFieldImage.getText();
        String day = jTextFieldDay.getText();
        String time = jTextFieldTime.getText();

        Movie tempMovie = null;
        tempMovie = new Movie(previousMovie.getId(), type, name, introduction, actor, director, country, length, image, day, time);

        try {
            movieDAO.updateMovie(tempMovie);
            setVisible(false);
            dispose();
            movieGUI.process();
            JOptionPane.showMessageDialog(movieGUI, "Movie updated succesfully", "Movie Update", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(
                    movieGUI,
                    "Error update Movie: "
                    + exc.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelActor;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelIntroduction;
    private javax.swing.JLabel jLabelLength;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaIntroduction;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldActor;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldImage;
    private javax.swing.JTextField jTextFieldLength;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldTime;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
